### ISSUE TITLE
Reproducing results for KITTI

### ISSUE THREAD

**Issue by hgolestaniii** [DepthAnything/Video-Depth-Anything#63]
Hello,

I want to reproduce the results published in Table1 for KITTI. I have doubt which drives/frames have been used for the evaluation.

1- Should I use all images inside "KITTI Eigen Split" (i.e., 652 images with valid gt depth)? If yes, should I find an optimum "scale", and "shift" per drive? or per the whole Eigen Split dataset? You know, we have 28 drives there.
2- In the paper (4.1 Evaluation) you mentioned that unlike "DepthCrafter" you use up to 500 images for evaluation? How do you select those 500 images for KITTI? Are they part of Eigen Split (652 images)? Do those 500 images belong to the same drive? or they are from different drives?

Thanks.

**Comment by guohengkai** [comment]
Hi, @hgolestaniii 
We have released the codes for benchmark. See this: https://github.com/DepthAnything/Video-Depth-Anything/tree/main/benchmark

**Comment by hgolestaniii** [comment]
Hi @guohengkai,

Many thanks for your reply!

Wonderful. As far as I understood, you don't run evaluation on Eigen split and run it on a subset of original KITTI dataset. I have looked into the code inside /benchmark, but still have a question:

- In the KITTI depth estimation dataset (ground truth depth) you see two folders: "train", and "val". Did you use all drives in both "train", and "val" for benchmarking, or you used only data inside "val"?

Many thanks :)
